<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <script>
            let kg = 7

            kg +=5

            console.log(kg)

            //2 tapsirma

            let a = 7
            let b = 93

            b += a

            console.log(b)

            //3 tapsirma 

            let a_stakan = "pepsi"
            let b_stakan = "cola"
            let s_stakan = "suw"

            
            let pustoy_stakan = b_stakan

            b_stakan = s_stakan
            s_stakan = a_stakan
            a_stakan = pustoy_stakan


            console.log(a_stakan)
            console.log(b_stakan)
            console.log(s_stakan)

            //4 tapsirma

            let firstname = "Azamat"
            let age = 20.8
            let studenba = false // Awa student

            console.log(typeof(firstname))
            console.log(typeof(age))
            console.log(typeof(studenba))

            //5 tapsirma

            let miywe = 'Banan'
            let suwma = 27000
            let = 3

            console.log(` ${miywe}`,  `bahasi ${suwma}`, `${3} kg bahasi 81000 sum boladi` )
        </script>
    </body>
</html>
